### ISSUE TITLE
docker toolbox: how to access container

### ISSUE THREAD

**Issue by AKAlias** [kuklinistvan/docker-anki-sync-server#1]
Hi Istvan!

Thanks for you great work here.

However, I can only get to run the sync-server via the kitematic GUI of the Docker Toolbox (regular x64 Docker does not work on W10 Home). 

When I create the anki-sync-server repo from you repo (btw. you don't have "latest" tag in your repo), the server runs.

But I cannot figure out how to access the container now and setup the user, collection etc. 

Am I missing something?

Thank you

**Comment by kuklinistvan** [comment]
Hi AKAlias!

Thank you for your valuable feedback!

I've just created the missing latest tag.

In Kitematic GUI what you need to look for is an option to launch a terminal session in your container. Actually, in a native Linux environment, this is what you would do if you follow [the instructions](https://github.com/kuklinistvan/docker-anki-sync-server#creating-users).

In a Linux environment, if you execute the command:

```
# docker exec -it anki-container /bin/sh
```
then you will get a prompt in your container:
```
/app/anki-sync-server #
```

In case of the Kitematic GUI on Windows or OS X you should have a button to launch a terminal session at the top of the window, [according to the manual](https://docs.docker.com/kitematic/userguide/#starting-a-terminal-in-a-container).

From there, you should be able to access the `ankisyncctl.py` tool in the container home directory:
```
/app/anki-sync-server # ./ankisyncctl.py --help
usage: ./ankisyncctl.py <command> [<args>]

Commands:
  adduser <username> - add a new user
  deluser <username> - delete a user
  lsuser             - list users
  passwd <username>  - change password of a user
```

This is the tool you can use to manage your server. For example, to create a user you may execute the command
```
/app/anki-sync-server # ./ankisyncctl.py adduser USERNAME
Enter password for USERNAME:
/app/anki-sync-server #
```

Please also make sure to mount the `/app/data` directory of your container to a directory on your physical host or to a volume (this is where your actual data, like your collections are stored), otherwise you may lose your server data if you re-create or remove the container itself.

Good luck, and thanks again!

**Comment by AKAlias** [comment]
Hi kuklinistvan, 

thanks for your reply and sorry for my delay. Horribly enough, it is not working despite your input. 

If I start the container in kitematic gui up and access the console the following happens:

</app/anki-sync-server # # docker exec -it anki-container /bin/sh
</app/anki-sync-server # docker exec -it anki-container /bin/sh
sh: docker: not found
/app/anki-sync-server # exec -it anki-container /bin/sh
sh: exec: illegal option -i
/app/anki-sync-server # /app/anki-sync-server #
sh: /app/anki-sync-server: Permission denied
/app/anki-sync-server # /app/anki-sync-server # ./ankisyncctl.py --help
sh: /app/anki-sync-server: Permission denied

I am not entirely sure what I am missing. Sorry - I am quite new to the container/docker universe.

Thanks for your support!

**Comment by kuklinistvan** [comment]
Hello again,

The command I have mentioned before drops you to the shell of your container on a Linux host (and it also assumes that you have given the container the name `anki-container`):
```
# docker exec -it anki-container /bin/sh
```
It does exactly the same as accessing the console on Kitematic GUI that you mentioned. You shouldn't use the command above, as your host is Windows 10 Home which uses a third party tool (Kitematic) to emulate an environment Docker is capable running in (thus, in Windows 10 command line the command probably won't work). I have written it only to show you an analogy between the commands of the original README of this repository and Kitematic. After accessing the console on Kitematic GUI using the button, you may see something similar to this:

```
/app/anki-sync-server #
```

This IS the prompt of your container. You are not meant to execute a command IN your container that is for accessing the container from the outside. You are already facing the prompt of your container - that step is done.

I have written an example in my previous answer on how to use `ankisyncctl.py` tool. (You can find one in the README too.)

I have shown this:

```
/app/anki-sync-server # ./ankisyncctl.py --help
usage: ./ankisyncctl.py <command> [<args>]

Commands:
  adduser <username> - add a new user
  deluser <username> - delete a user
  lsuser             - list users
  passwd <username>  - change password of a user
```

Now the important part: from all of the above, `./ankisyncctl.py --help` is what you type, not the whole line. `/app/anki-sync-server #` is part of the prompt. The rest of it is the output of the command.

I think this is actually not a problem of Docker being new for you but basic shell usage. Looking up some tutorials on how to use `bash` could be a good idea before making experiments with Docker.

Good luck and keep going! ;)
