### ISSUE TITLE
SyncRedirector only works with Anki 2.1.19 (MacOSx)

### ISSUE THREAD

**Issue by julian-yang** [kuklinistvan/docker-anki-sync-server#22]
* **AnkiDesktop version number:** 2.1.19
* **AnkiDroid version number:**

## Summary

Reproduction (what did you do - the more details you give, the better):
Install Anki desktop version (mac) I've tried 2.1.15, 2.1.23, 2.1.15
What was expected to happen:
Be able to install SyncRedirector via the extension # (2124817646)

What happened instead (the more details you give, the better):
Anki gives an error saying that the plugin doesn't support my current Anki version

Luckily you have 2.1.19 linked on your github page, as I wasn't able to find it on apps.ankiweb.net.

Just wanted to let you know. Thanks!

**Comment by kuklinistvan** [comment]
Hello there,

Thank you for notifying me! Actually, I'm aware of it and it is intentional, see the reasoning here: https://github.com/kuklinistvan/docker-anki-sync-server/issues/16#issuecomment-626304807.

Short version: it is my preference to support less versions to ensure greater stability. Right now 2.1.19 is supported by this repository and I more or less follow the original server project's supported Anki version. You can, however, always fork SyncRedirector if you wish to support more recent versions of Anki.

I'm closing this issue now, but feel free to reopen if you have any further suggestions or questions!
