### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by senorsmile** [kuklinistvan/docker-anki-sync-server#3]
I'm getting the following error when trying to test this with the docker image running locally: 

```python
Syncing failed:
Traceback (most recent call last):
  File "/usr/share/anki/aqt/sync.py", line 340, in run
    self._sync()
  File "/usr/share/anki/aqt/sync.py", line 365, in _sync
    self.hkey = self.server.hostKey(*self.auth)
  File "/usr/share/anki/anki/sync.py", line 599, in hostKey
    self.hkey = json.loads(ret.decode("utf8"))['key']
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This is on a new deck in the anki gui.  When I click sync, it asks me for the username and password (which I set up by entering the running image) and then immediately gives me the above error.

**Comment by kuklinistvan** [comment]
Hello there,

Unfortunately I was unable to reproduce the bug with Anki Desktop version 2.1.8.

I think I could use some additional information that may help me recreate your scenario in order to find the root of the problem. Could you supply me the clues below?

- Your version of Anki Desktop
- The deployment method (did you follow the one-time or the server installation instructions?)
- Docker invocation command
- Output of `$ tree ~/.local/share/Anki2/addons21`
- Output of `$ cat ~/.local/share/Anki2/addons21/MySyncServer/__init__.py`
- Output of `$ docker logs anki-container`
- The exact manipulation of the GUI, click-by-click :)
- Anything else you find relevant

You may use a pastebin container for the longer chunks of log and output.

Thank you for opening the issue!

**Comment by senorsmile** [comment]
* Version of anki: Version 2.1.0beta36 (this is from ubuntu 18.04's repo)
* deployment method - one time instructions (except the data dir is already owned by root) (and yes, this has been running without exiting since I first tried, so it hasn't been removed yet on exit)
* docker invocation:
```bash
sudo docker run -it    --mount type=bind,source="$ANKI_SYNC_DATA_DIR",target=/app/data    -p 27701:27701    --name anki-container    --rm    kuklinistvan/anki-sync-server:tsudoku-2.1.4```
* addons dir: 
```/home/senorsmile/.local/share/Anki2/addons21
└── ankisyncd
    ├── __init__.py
    └── __pycache__
        └── __init__.cpython-36.pyc
```
* I called the file differently `ankisyncd`, ```
$ cat .local/share/Anki2/addons21/ankisyncd/__init__.py 
import anki.sync
anki.sync.SYNC_BASE = 'http://127.0.0.1:27701/' + '%s'
anki.sync.SYNC_MEDIA_BASE = 'http://127.0.0.1:27701/msync/' + '%s'
```
* docker logs: ```
Creating new configuration file: ankisyncd.conf.
Creating new authentication database: auth.db.
Creating collections directory: collections.
Starting tsudoko's anki-sync-server
INFO:root:Loaded config from /app/anki-sync-server/ankisyncd.conf
INFO:root:Serving HTTP on 0.0.0.0 port 27701...
172.17.0.1 - - [25/Feb/2019 04:00:10] "GET /sync/meta HTTP/1.1" 403 157
172.17.0.1 - - [25/Feb/2019 04:00:10] "GET /favicon.ico HTTP/1.1" 200 16
172.17.0.1 - - [25/Feb/2019 04:07:21] "POST /%25ssync/hostKey HTTP/1.1" 200 16
172.17.0.1 - - [25/Feb/2019 04:10:55] "POST /%25ssync/hostKey HTTP/1.1" 200 16
172.17.0.1 - - [25/Feb/2019 04:16:51] "POST /%25ssync/meta HTTP/1.1" 200 16
172.17.0.1 - - [25/Feb/2019 04:16:54] "POST /%25ssync/meta HTTP/1.1" 200 16
172.17.0.1 - - [25/Feb/2019 04:16:56] "POST /%25ssync/meta HTTP/1.1" 200 16
```
* gui, click-by-click
** open anki
** hit `y` key (for sync)
** in the account required screen, enter username and password I created with ankisyncctl.py while exec'd into the running container
** click OK

Oddly enough, the error is not happening today, but I get a `Ankiweb ID or password was incorrect; please try again`.  I changed the password using ankisyncctl.py and got the same thing.

**Comment by senorsmile** [comment]
I'm going to clean up everything and try again from scratch using your `Deploying on a server` instructions.  Will post back with results.

**Comment by senorsmile** [comment]
I tried it from ankidroid and all is working as expected.  It appears to be a problem with the old version of anki in Ubuntu 18.04.  

I tried to install from source.  Available version is 2.1.9.  I spun up a vm to keep separate from my main OS installation.  I got a completely different error on that version: 
```
Syncing failed:
AnkiWeb encountered an error. Please try again in a few minutes, and if the problem persists, please file a bug report.
```

The server logs show: 
```
ValueError: invalid literal for int() with base 10: '9 (ae67c976)'
```

This is probably a different issue at this point.  

Is there a good way to download previous tars of Anki?  I don't seem to be able to find them.

**Comment by kuklinistvan** [comment]
Hello again,

Thank you very much for collecting all these details!

I've recently created a new tag on DockerHub for AnkiDesktop version 2.1.9 because of the issue you have encountered (see #4).

May I kindly ask you to do another test run? This time, please ensure, that:

* You're using Anki Desktop version 2.1.9. **downloaded from the official website**
https://apps.ankiweb.net/downloads/current/anki-2.1.9-linux-amd64.tar.bz2

(If I remember well they have mentioned some trouble related to the packages of some of the Linux distributions due to some library version mismatch)

* You're using the latest AnkiDroid version from Google Play
* Invoke Docker with the one-time instructions, specifying the 2.1.9 tag

```bash
export ANKI_SYNC_DATA_DIR=~/anki-sync-server-docker-data

mkdir -p "$ANKI_SYNC_DATA_DIR"
docker run -it \
   --mount type=bind,source="$ANKI_SYNC_DATA_DIR",target=/app/data \
   -p 27701:27701 \
   --name anki-container \
   --rm \
   kuklinistvan/anki-sync-server:tsudoku-2.1.9
```

If it works for you then I will probably update the README.md and the `latest` Docker tag soon.

**Comment by senorsmile** [comment]
I've been too busy but will try this out today and post back with the results.

**Comment by senorsmile** [comment]
confirmed... this is now working on 2.1.9 (desktop).   

Thanks for all of your help and the effort you've put in to maintain this image!
